export const cards = [
  {
    id: 1,
    title: "AI Artists",
    desc: "Add talent to AI",
    img: "/cards/card_1.jpeg",
  },
  {
    id: 2,
    title: "Logo Design",
    desc: "Build yor brand",
    img: "/cards/card_2.webp",
  },
  {
    id: 3,
    title: "WordPress",
    desc: "Customize your site",
    img: "/cards/card_3.jpeg",
  },
  {
    id: 4,
    title: "Voice Over",
    desc: "Share your message",
    img: "/cards/card_4.webp",
  },
  {
    id: 5,
    title: "Video Explainer",
    desc: "Engage your audience",
    img: "/cards/card_5.webp",
  },
  {
    id: 6,
    title: "Social Media",
    desc: "Reach more customers",
    img: "/cards/card_6.webp",
  },
  {
    id: 7,
    title: "SEO",
    desc: "Unlock growth online",
    img: "/cards/card_7.jpeg",
  },
  {
    id: 8,
    title: "Illustration",
    desc: "Color you dreams",
    img: "/cards/card_8.jpeg",
  },
];

export const projects = [
  {
    id: 1,
    img: "/projectCards/catCard_1.jpeg",
    pp: "/projectCards/pp_1.webp",
    cat: "Web and Mobile Design",
    username: "Anna Bell",
  },
  {
    id: 2,
    img: "/projectCards/catCard_2.jpeg",
    pp: "/projectCards/pp_2.webp",
    cat: "Logo Design",
    username: "Morton Green",
  },
  {
    id: 3,
    img: "/projectCards/catCard_3.webp",
    pp: "/projectCards/pp_3.jpeg",
    cat: "Animated GIFs",
    username: "Emmett Potter",
  },
  {
    id: 4,
    img: "/projectCards/catCard_4.webp",
    pp: "/projectCards/pp_4.webp",
    cat: "Packaging Design",
    username: "Freddie Johnston",
  },
  {
    id: 5,
    img: "/projectCards/catCard_5.webp",
    pp: "/projectCards/pp_5.webp",
    cat: "Social Media Design",
    username: "Audrey Richards",
  },
  {
    id: 6,
    img: "/projectCards/catCard_6.webp",
    pp: "/projectCards/pp_6.webp",
    cat: "Illustration",
    username: "Dalton Hudson",
  },
  {
    id: 7,
    img: "/projectCards/catCard_7.webp",
    pp: "/projectCards/pp_7.webp",
    cat: "Book Design",
    username: "Hannah Dougherty",
  },
  {
    id: 8,
    img: "/projectCards/catCard_8.webp",
    pp: "/projectCards/pp_8.jpeg",
    cat: "Digital Marketing",
    username: "Ward Brewer",
  },
];

export const gigs = [
  {
    id: 1,
    img: "/gigs/pic_1.jpeg",
    pp: "/gigs/profile_1.webp",
    desc: "I will create ai art character from your images and prompts",
    price: 59,
    star: 5,
    username: "Anna Bell",
  },
  {
    id: 2,
    img: "/gigs/pic_2.jpeg",
    pp: "/gigs/profile_2.webp",
    desc: "I will create ultra high quality character art with ai",
    price: 79,
    star: 5,
    username: "Lannie Coleman",
  },
  {
    id: 3,
    img: "/gigs/pic_3.webp",
    pp: "/gigs/profile_3.webp",
    desc: "I will creating unique ai generated artworks mid journey ai artist",
    price: 112,
    star: 5,
    username: "Carol Steve",
  },
  {
    id: 4,
    img: "/gigs/pic_4.webp",
    pp: "/gigs/profile_4.jpeg",
    desc: "I will create custom ai generated artwork using your photos",
    price: 99,
    star: 4,
    username: "Don Weber",
  },
  {
    id: 5,
    img: "/gigs/pic_5.webp",
    pp: "/gigs/profile_5.webp",
    desc: "I will recreate your dreams in high quality pictures",
    price: 59,
    star: 5,
    username: "Audrey Richards",
  },
  {
    id: 6,
    img: "/gigs/pic_6.jpeg",
    pp: "/gigs/profile_6.jpeg",
    desc: "I will create ai digital art illustration hyper realistic painting",
    price: 79,
    star: 4,
    username: "Walton Shepard ",
  },
  {
    id: 7,
    img: "/gigs/pic_7.jpeg",
    pp: "/gigs/profile_7.webp",
    desc: "I will generate images with your prompts using ai dalle",
    price: 89,
    star: 5,
    username: "Waverly Schaefer",
  },
  {
    id: 8,
    img: "/gigs/pic_8.webp",
    pp: "/gigs/profile_8.webp",
    desc: "I will create custom art using midjourney generator",
    price: 110,
    star: 4,
    username: "Wilton Hunt",
  },
];